CREATE TABLE STORE
(
  Store_Name VARCHAR(100) NOT NULL,
  Address_line_1 VARCHAR(100) NOT NULL,
  City VARCHAR(100) NOT NULL,
  State VARCHAR(100) NOT NULL,
  Zip INT NOT NULL,
  Phone_Number INT NOT NULL,
  PRIMARY KEY (Store_Name),
  UNIQUE (Phone_Number)
);

CREATE TABLE EMPLOYEE
(
  ID INT NOT NULL,
  Name VARCHAR(100) NOT NULL,
  Wage FLOAT NOT NULL,
  Address_line_1 VARCHAR(100) NOT NULL,
  City VARCHAR(100) NOT NULL,
  State VARCHAR(100) NOT NULL,
  Zip INT NOT NULL,
  DOB VARCHAR(100) NOT NULL,
  Store_Name VARCHAR(100) NOT NULL,
  PRIMARY KEY (ID),
  FOREIGN KEY (Store_Name) REFERENCES STORE(Store_Name)
);

CREATE TABLE CUSTOMER_ACCOUNT
(
  Account_ID INT NOT NULL,
  Email VARCHAR(100) NOT NULL,
  Phone_Number INT NOT NULL,
  Address_line_1 VARCHAR(100) NOT NULL,
  City VARCHAR(100) NOT NULL,
  State VARCHAR(100) NOT NULL,
  Zip INT NOT NULL,
  Name VARCHAR(100) NOT NULL,
  DOB VARCHAR(100) NOT NULL,
  PRIMARY KEY (Account_ID)
);

CREATE TABLE AFTERMARKET_INVENTORY
(
  GPU_Name VARCHAR(100) NOT NULL,
  GPU_Quantity INT NOT NULL,
  Store_Name VARCHAR(100) NOT NULL,
  PRIMARY KEY (GPU_Name),
  FOREIGN KEY (Store_Name) REFERENCES STORE(Store_Name)
);

CREATE TABLE MANUFACTURER
(
  Name VARCHAR(100) NOT NULL,
  Contact_Number INT NOT NULL,
  Address_line_1 VARCHAR(100) NOT NULL,
  City VARCHAR(100) NOT NULL,
  State VARCHAR(100) NOT NULL,
  Zip INT NOT NULL,
  Store_Name VARCHAR(100) NOT NULL,
  PRIMARY KEY (Name),
  FOREIGN KEY (Store_Name) REFERENCES STORE(Store_Name),
  UNIQUE (Contact_Number)
);

CREATE TABLE STOCK_INVENTORY
(
  GPU_Name VARCHAR(100) NOT NULL,
  GPU_Quantity INT NOT NULL,
  Store_Name VARCHAR(100) NOT NULL,
  PRIMARY KEY (GPU_Name),
  FOREIGN KEY (Store_Name) REFERENCES STORE(Store_Name)
);

CREATE TABLE CUSTOMER
(
  ID INT NOT NULL,
  Payment_Method VARCHAR(100) NOT NULL,
  Payment_Amount FLOAT NOT NULL,
  Items_Purchased INT NOT NULL,
  Card_Number INT NULL,
  Store_Name VARCHAR(100),
  PRIMARY KEY (ID),
  FOREIGN KEY (Store_Name) REFERENCES STORE(Store_Name),
  FOREIGN KEY (ID) REFERENCES CUSTOMER_ACCOUNT(Account_ID)
);

CREATE TABLE GPU
(
  GPU_Name VARCHAR(100) NOT NULL,
  GPU_Retail_Price FLOAT NOT NULL,
  GPU_Wholesale_Price FLOAT NOT NULL,
  Architecture VARCHAR(100) NOT NULL,
  Power_Requirement INT NOT NULL,
  VRAM INT NOT NULL,
  Clock_Speed INT NOT NULL,
  Manufacturer VARCHAR(100) NOT NULL,
  PRIMARY KEY (GPU_Name),
  FOREIGN KEY (GPU_Name) REFERENCES STOCK_INVENTORY(GPU_Name),
  FOREIGN KEY (GPU_Name) REFERENCES AFTERMARKET_INVENTORY(GPU_Name)
);